main.py
from flask import Flask, render_template
from routes.auth import auth_bp
from routes.cadastro import cadastro_bp
from routes.bd_cad import bd_bp
from flask import Flask
from static.functions import init_DB

app = Flask(__name__)

app.config['SECRET_KEY'] = 'projetofacom'
init_DB()

app.register_blueprint(auth_bp)
app.register_blueprint(cadastro_bp)
app.register_blueprint(bd_bp, url_prefix='/bd')


@app.route('/')
def homepage():
    return render_template('index.html')


if '__main__' == __name__:
    app.run(debug=True, port=80)

routes/auth.py
from flask import Blueprint, session, request, redirect, url_for, flash
from database.cadastro import user

auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/', methods=['POST'])
def auth():
    session.clear()
    email = request.form.get('email')
    senha = request.form.get('senha')
    if email == user['email'] and senha == user['senha']:
        session['email'] = email
        session['senha'] = senha
        return redirect(url_for('cadastro.homepage_cad'))
    flash('Login inválido')
    return redirect(url_for('homepage'))

@auth_bp.route('/logout')
def logout():
    session.pop('email')
    session.pop('senha')
    print(session)
    return redirect('/')

routes/bd_cad.py
from flask import Blueprint, render_template, request, flash, session, redirect, url_for
from database.cadastro import user
from static.functions import to_dict_user, get_db_connection

bd_bp = Blueprint('bd', __name__)
nomes = ['Código','Nome', 'CPF', 'Raça', 'Gênero', 'Escolaridade', 'Email', 'Data de Nascimento']

@bd_bp.route('/')
def bd_home():
    return render_template('home-bd.html')

@bd_bp.route('/delete', methods=['DELETE'])
def delete():
    data = request.get_json()
    try:
        db = get_db_connection()
        if not db:
            return {"message": "Erro ao conectar ao Banco de dados"}
        cursor = db.cursor()
        cursor.execute(f"DELETE FROM Pessoa WHERE id_Pessoa = {data['codigo']}")
        cursor.execute(f"DELETE FROM Etnia_Pessoa WHERE id_Pessoa = {data['codigo']}")
        db.commit()
        db.close()
    except Exception as e:
        return {"message": f"Erro ao deletar usuário, {e}"}
        
    return {'ok': 'ok'}

@bd_bp.route('/content')
def content():
    try:
        db = get_db_connection()
        if not db:
            return {"message": "Erro ao conectar ao Banco de dados"}
        cursor = db.cursor()
        cursor.execute(f"SELECT * FROM Pessoa")
        cad = cursor.fetchall()
        db.close()
    except Exception as e:
        return {"message": f"Erro ao carregar conteúdo, {e} "}

    return render_template('itens-table.html', cad= cad)

@bd_bp.route('/get_user/<cod>')
def details(cod):
    data = to_dict_user(cod)
    return render_template('detail.html', dados=data)

@bd_bp.before_request
def authentication():
    if not 'email' in session:
        flash('Faça o login para acessar esta página')
        return redirect(url_for('homepage'))
    if session['email'] != user['email'] or session['senha'] != user['senha']:
        flash('Faça o login para acessar esta página')
        return redirect(url_for('homepage'))
    

routes/cadastro.py
from flask import Blueprint, session, request, redirect, url_for, render_template, flash, jsonify
from database.cadastro import user
from static.functions import formata_cpf, verifica_cpf, verifica_user, salva_user, code_etnia, vetor_etnia, add_etnia

cadastro_bp = Blueprint('cadastro', __name__)

etnia_var = ['Kadiwéls', 'Guaraní', 'Guaicurus', 'Outro']

user_atual = {}

@cadastro_bp.route('/cadastro/')
def homepage_cad():
    return render_template('home-cad.html')

@cadastro_bp.route('/cadastro/nome')
def nome():
    return render_template('nome.html')

@cadastro_bp.route('/cadastro/nome', methods=['POST'])
def nome_v():
    nome = request.form.get('nome')
    v_nome = nome.split(' ')
    for i in v_nome:
        if not i.isalpha():
            flash('Digite apenas letras')
            return redirect(url_for('cadastro.nome'))
    user_atual.update({'nome': nome}) 
    print(user_atual)
    return redirect(url_for('cadastro.cpf'))


@cadastro_bp.route('/cadastro/cpf')
def cpf():
    return render_template('cpf.html')

@cadastro_bp.route('/cadastro/cpf', methods=['POST'])
def cpf_v():
    cpf = request.form.get('cpf')
    if len(cpf) == 14:
        cpf = formata_cpf(cpf)
        if cpf:
            if verifica_cpf(int(cpf)):
                user_atual.update({'CPF': cpf}) 
                print(user_atual)
                return redirect(url_for('cadastro.genero'))
            flash('Digite um CPF válido')    
            return redirect(url_for('cadastro.cpf'))
        flash('Digite apenas os números')
    else:
        flash('Digite ao menos 11 dígitos')
    return redirect(url_for('cadastro.cpf'))


@cadastro_bp.route('/cadastro/genero')
def genero():
    return render_template('sexo.html')

@cadastro_bp.route('/cadastro/genero', methods=['POST'])
def genero_v():
    try:
        data = request.form['gender']
        print(data)
    except:
        flash('Selecione uma das opções')
        return redirect(url_for('cadastro.genero'))
    user_atual.update({'genero': data}) 
    return redirect(url_for('cadastro.raca'))


@cadastro_bp.route('/cadastro/raca')
def raca():
    return render_template('raca.html')

@cadastro_bp.route('/cadastro/raca', methods=['POST'])
def raca_v():
    data = request.form['raca']
    print(data)
    user_atual.update({'raca': data}) 
    return redirect(url_for('cadastro.etnia'))


@cadastro_bp.route('/cadastro/etnia')
def etnia():
    return render_template('etnia.html')

@cadastro_bp.route('/cadastro/etnia', methods=['POST'])
def etnia_v():
    data = request.form['etnia']
    
    if(data.lower() == 'outro(a)'):
        return redirect(url_for('cadastro.etnia_add'))
    etnia = code_etnia(data)
    print(etnia)
    user_atual.update({'etnia': etnia}) 
    
    return redirect(url_for('cadastro.nasc'))

@cadastro_bp.route('/cadastro/etnia/add')
def etnia_add():
    return render_template('etnia_add.html')

@cadastro_bp.route('/cadastro/etnia/add', methods=['POST'])
def etnia_add_v():
    data = request.form['etnia']
    print(data)
    add_etnia(data)
    etnia = code_etnia(data)
    user_atual.update({'etnia': etnia}) 
    return redirect(url_for('cadastro.nasc'))

@cadastro_bp.route('/get/etnia')
def etnia_get():
    etnia = vetor_etnia()
    etnia.append('Outro(a)')
    dict = {
        'etnia': etnia
    }
    var = jsonify(dict)
    return var

@cadastro_bp.route('/cadastro/nascimento')
def nasc():
    return render_template('datetime.html')

@cadastro_bp.route('/cadastro/nascimento', methods=['POST'])
def nasc_v():
    data = request.form.get('data')
    date = data.split('-')
    data = f"{date[2]}/{date[1]}/{date[0]}"
    user_atual.update({'nascimento': data}) 
    return redirect(url_for('cadastro.escolaridade'))


@cadastro_bp.route('/cadastro/escolaridade')
def escolaridade():
    return render_template('escolaridade.html')

@cadastro_bp.route('/cadastro/escolaridade', methods=['POST'])
def escolaridade_v():
    data = request.form['esc']
    user_atual.update({'escolaridade': data}) 
    return redirect(url_for('cadastro.email'))


@cadastro_bp.route('/cadastro/email')
def email():
    return render_template('email.html')

@cadastro_bp.route('/cadastro/email', methods=['POST'])
def email_v():
    data = request.form.get('email')
    user_atual.update({'email': data}) 
    return redirect(url_for('cadastro.fim'))

@cadastro_bp.route('/cadastro/fim')
def fim():
    aux = verifica_user(user_atual)
    if not aux:
        flash('Ocorreu um erro ao realizar o seu cadastro, por favor refaça-o!')
        return redirect(url_for('cadastro.homepage_cad'))
    cod = salva_user(aux)
    user_atual.clear()
    return render_template('fim.html', codigo=cod)

@cadastro_bp.before_request
def authentication():
    if not 'email' in session:
        flash('Faça o login para acessar esta página')
        return redirect(url_for('homepage'))
    if session['email'] != user['email'] or session['senha'] != user['senha']:
        flash('Faça o login para acessar esta página')
        return redirect(url_for('homepage'))
    

templates/cpf.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename= 'campos.css') }}">
    <title>Página dados CPF</title>
</head>
<body>
    {% set mensagens = get_flashed_messages() %}
    {%if mensagens[0]:%}
    <script>
        window.alert('{{mensagens[0]}}')
    </script>
    {%endif%}
    <main class="input">
        <h1>COLOQUE AQUI O SEU CPF</h1>
        <div class="variaveis-py">{{ progresso }}</div>
        <form action="{{ url_for('cadastro.cpf_v') }}" method="post" class="form" id="form">    
            <input type="text" id="cpf" placeholder="Digite aqui..." name="cpf" required> 
        </form>    
    </main>
    <footer class="div_botao">    
        <button class="botao" onclick="window.location.assign('/cadastro/nome')" id="anterior"> <= Anterior</button>
        <div class="meio">
            <section class="progresso">
                <div class="range">
                    <div class="completado"></div>
                </div>
                <h3>% Completado</h3>
            </section>
            <aside><span>&#169;</span> made by UFMS</aside>
        </div>
            <button class="botao"  form="form"  type="submit" id="proximo">Próxima =></button>
    </footer>
    <script src="{{ url_for('static', filename= 'cru.js') }}"></script>
</body>
</html>

templates/datetime.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página dados Nascimento</title>
    <link rel="stylesheet" href="{{ url_for('static', filename= 'campos.css') }}">
</head>
<body>
    <main class="input">
        <h1>SELECIONE SUA DATA DE NASCIMENTO</h1>
        <div class="variaveis-py">{{ progresso }}</div>
        <form action="{{url_for('cadastro.nasc_v')}}" method="post" class="form" id="form">    
            <input type="date" id="data" placeholder="Digite aqui..." name="data" required> 
        </form>    
    </main>
    <footer class="div_botao">    
        <button class="botao" onclick="window.location.assign('/cadastro/etnia')" id="anterior"> <= Anterior</button>
        <div class="meio">
            <section class="progresso">
                <div class="range">
                    <div class="completado"></div>
                </div>
                <h3>% Completado</h3>
            </section>
            <aside><span>&#169;</span> made by UFMS</aside>
        </div>
            <button class="botao"  form="form"  type="submit" id="proximo">Próxima =></button>
    </footer>
</body>
</html>

templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="teste">

        <table>
            <thead>
                <tr>
                    <span>x</span>
                    <th>Tipo</th>
                    <th>Conteúdo</th>
                </tr>
            </thead>
            <tbody>
                {%for i in dados%}
                <tr>
                    <td class="codigo">{{ i }}</td>
                    <td>{{ dados[i] }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    
</body>
</html>

templates/email.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename= 'campos.css') }}">
    <title>Página dados Email</title>
</head>
<body>
        <main class="input">
            <h1>COLOQUE AQUI O SEU E-MAIL</h1>
            <div class="variaveis-py">{{ progresso }}</div>
            <form action="{{ url_for('cadastro.email_v') }}" method="post" class="form" id="form">    
                <input type="email" id="email" placeholder="Digite aqui..." name="email" required> 
            </form>    
        </main>
        <footer class="div_botao">    
            <button class="botao" onclick="window.location.assign('/cadastro/escolaridade')" id="anterior"> <= Anterior</button>
            <div class="meio">
                <section class="progresso">
                    <div class="range">
                        <div class="completado"></div>
                    </div>
                    <h3>% Completado</h3>
                </section>
                <aside><span>&#169;</span> made by UFMS</aside>
            </div>
                <button class="botao"  form="form"  type="submit" id="proximo">Próxima =></button>
        </footer>
</body>
</html>

templates/escolaridade.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename= 'options.css') }}">

    <title>Página dados Escolaridade</title>
</head>
<body>
    <main class="input">
        <h1>SELECIONE O SEU NÍVEL DE ESCOLARIDADE</h1>
        <div class="variaveis-py">{{ progresso }}</div>
        <form action="{{ url_for('cadastro.escolaridade_v') }}" method="post" class="form" id="form-g">
            <div class="item-grande">
                <input type="radio" name="esc" value="EF1" required>
                <label for="EF1" class="radio">Da 1ª à 4ª série do Ensino Fundamental (antigo primário)</label>
            </div>
            <div class="item-grande">
                <input type="radio" name="esc" value="EF2">
                <label for="EF2" class="radio">Da 5ª à 8ª série do Ensino Fundamental (antigo ginásio)</label>
            </div>
            <div class="item-grande">
                <input type="radio" name="esc" value="EM">
                <label for="EM" class="radio">Ensino Médio (antigo 2º grau)</label>
            </div>
            <div class="item-grande">
                <input type="radio" name="esc" value="EJA">
                <label for="EJA" class="radio">Educação de Jovens e Adultos</label>
            </div>
            <div class="item-grande">
                <input type="radio" name="esc" value="NE">
                <label for="NE" class="radio">Não estudou</label>
            </div>
            <div class="item">
                <input type="radio" name="esc" value="outro">
                <label for="outro" class="radio">Não Sei</label>
            </div>
        </form>
    </main>
    <footer class="div_botao">    
        <button class="botao" onclick="window.location.assign('/cadastro/nascimento')" id="anterior"> <= Anterior</button>
        <div class="meio">
            <section class="progresso">
                <div class="range">
                    <div class="completado"></div>
                </div>
                <h3>% Completado</h3>
            </section>
            <aside><span>&#169;</span> made by UFMS</aside>
        </div>
            <button class="botao"  form="form-g"  type="submit" id="proximo">Próxima =></button>
    </footer>
    <script src="{{ url_for('static', filename= 'script.js') }}"></script>
</body>
</html>

templates/etnia.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename= 'etnia.css') }}">
    <title>Página dados Email</title>
</head>
<body>
    <main class="input">
        <h1>ESCOLHA A SUA ETNIA</h1>
        <div class="variaveis-py">{{ progresso }}</div>
        <form action="{{ url_for('cadastro.etnia_v') }}" method="post" class="form" id="form">
            <input type="text" id="etnia" placeholder="Digite aqui..." name="etnia" required autocomplete="off"> 
            <div class="datalist">
            </div> 
        </form>    
    </main>
    <footer class="div_botao">    
        <button class="botao" onclick="window.location.assign('/cadastro/raca')" id="anterior"> <= Anterior</button>
        <div class="meio">
            <section class="progresso">
                <div class="range">
                    <div class="completado"></div>
                </div>
                <h3>% Completado</h3>
            </section>
            <aside><span>&#169;</span> made by UFMS</aside>
        </div>
            <button class="botao"  form="form"  type="submit" id="proximo">Próxima =></button>
    </footer>
    <script src="{{ url_for('static', filename= 'search.js') }}"></script>
</body>
</html>

templates/etnia_add.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename= 'campos.css') }}">
    <title>Página dados Email</title>
</head>
<body>
    <main class="input">
        <h1>DIGITE QUAL A SUA ETNIA</h1>
        <div class="variaveis-py">{{ progresso }}</div>
        <form action="{{ url_for('cadastro.etnia_add_v') }}" method="post" class="form" id="form">
            <input type="text" id="etnia" placeholder="Digite aqui..." name="etnia" required autocomplete="off"> 
        </form>    
    </main>
    <footer class="div_botao">    
        <button class="botao" onclick="window.location.assign('/cadastro/etnia')" id="anterior"> <= Anterior</button>
        <div class="meio">
            <section class="progresso">
                <div class="range">
                    <div class="completado"></div>
                </div>
                <h3>% Completado</h3>
            </section>
            <aside><span>&#169;</span> made by UFMS</aside>
        </div>
            <button class="botao"  form="form"  type="submit" id="proximo">Próxima =></button>
    </footer>
</body>
</html>

templates/fim.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename= 'home.css') }}">

    <title>Homepage Cadastro</title>
</head>
<body>
    <h1>{{ codigo }}</h1>
    <p>Este é o seu código do participante</p>
    <button>Home</button>
    <div class="absolute">
        <a href="{{ url_for('bd.bd_home') }}">Ver cadastros</a>
    </div>
    <script>
        document.querySelector('button').addEventListener('click', () => {
            window.location.assign('/cadastro/')
        })
    </script>
</body>
</html>

templates/home-cad.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename= 'home.css') }}">

    <title>Homepage Cadastro</title>
</head>
<body>
    {% set mensagens = get_flashed_messages() %}
    {%if mensagens[0]:%}
    <script>
        window.alert('{{mensagens[0]}}')
    </script>
    {%endif%}
    <h1>Bem vindo à Página de Cadastros!</h1>
    <p>Coloque algumas informações para identificação antes das medições</p>
    <button>Iniciar</button>
    <div class="absolute">
        <a href="{{ url_for('bd.bd_home') }}">Ver cadastros</a>
    </div>
    <script>
        document.querySelector('button').addEventListener('click', () => {
            window.location.assign('/cadastro/nome')
        })
    </script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro FAC/FAN</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='cadastro.css') }}">
</head>
<body>
    {% set mensagens = get_flashed_messages() %}
    {%if mensagens[0]:%}
    <script>
        window.alert('{{mensagens[0]}}')
    </script>
    {%endif%}
    <header>
        <h1>Bem vindo!</h1>
        <p>Esta é a tela de cadastro para a obtenção de dados antropométricos</p>
    </head>

    <form action="/" method="post">
        <label for="email">Email:</label>
        <input type="email" placeholder="Digite aqui..." id="email" name="email">
        <label for="pwd">Senha:</label>
        <input type="text" placeholder="Digite aqui..." id="pwd" name="senha">
        <button type="submit" class="botao">Logar</button>
    </form>
</body>
</html>

templates/itens-table.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <table>
        <thead>
            <tr>
                <th>Código</th>
                <th>Nome</th>
                <th>CPF</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {%for i in cad%}
            <tr>
                <td class="codigo">{{ i[0] }}</td>
                <td>{{ i[1] }}</td>
                <td>{{ i[2] }}</td>
                <td class="buttons">
                    <button class="delete"><i class="fa-solid fa-trash"></i></button>
                    <button class="details"><i class="fa-solid fa-eye"></i></button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

templates/nome.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename= 'campos.css') }}">
    <title>Página dados Nome</title>
</head>
<body>
    {% set mensagens = get_flashed_messages() %}
    {%if mensagens[0]:%}
    <script>
        window.alert('{{mensagens[0]}}')
    </script>
    {%endif%}
    <main class="input">
        <h1>AGORA, DIGITE O SEU NOME</h1>
        <div class="variaveis-py">{{ progresso }}</div>
        <form action="{{ url_for('cadastro.nome_v') }}" method="post" class="form" id="form">    
            <input type="text" id="nome" placeholder="Digite aqui..." name="nome" required> 
        </form>    
    </main>
    <footer class="div_botao">    
        <button class="botao" onclick="window.location.assign('/cadastro/')" id="anterior"> <= Anterior</button>
        <div class="meio">
            <section class="progresso">
                <div class="range">
                    <div class="completado"></div>
                </div>
                <h3>% Completado</h3>
            </section>
            <aside><span>&#169;</span> made by UFMS</aside>
        </div>
            <button class="botao"  form="form"  type="submit" id="proximo">Próxima =></button>
    </footer>
</body>
</html>

templates/raca.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página dados Raça</title>
    <link rel="stylesheet" href="{{ url_for('static', filename= 'options.css') }}">
</head>
<body>
    {% set mensagens = get_flashed_messages() %}
    {%if mensagens[0]:%}
    <script>
        window.alert('{{mensagens[0]}}')
    </script>
    {%endif%}
    <main class="input">
        <h1>SELECIONE A SUA RAÇA SEGUNDO O IBGE</h1>
        <div class="variaveis-py">{{ progresso }}</div>
        <form action="{{ url_for('cadastro.raca_v') }}" method="post" class="form" id="form" >
            <div class="item">
                <input type="radio" name="raca" value="branco" required>
                <label for="branco">Branca</label>
            </div>
            <div class="item">

                <input type="radio" name="raca" value="pardo" >
                <label for="pardo">Parda</label>
            </div>
            <div class="item">

                <input type="radio" name="raca" value="preto" >
                <label for="preto">Preta</label>
            </div>
            <div class="item">

                <input type="radio" name="raca" value="amarelo" >
                <label for="amarelo">Amarela</label>
            </div>
            <div class="item">

                <input type="radio" name="raca" value="indigena">
                <label for="indigena">Indígena</label>
            </div>
        </form>
    </main>
    <footer class="div_botao">    
        <button class="botao" onclick="window.location.assign('/cadastro/genero')" id="anterior"> <= Anterior</button>
        <div class="meio">
            <section class="progresso">
                <div class="range">
                    <div class="completado"></div>
                </div>
                <h3>% Completado</h3>
            </section>
            <aside><span>&#169;</span> made by UFMS</aside>
        </div>
            <button class="botao"  form="form"  type="submit" id="proximo">Próxima =></button>
    </footer>
    <script src="{{ url_for('static', filename= 'script.js') }}"></script>
</body>
</html>

templates/sexo.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename= 'options.css') }}">

    <title>Seleção de Sexo</title>
</head>
<body>
    {% set mensagens = get_flashed_messages() %}
    {%if mensagens[0]:%}
    <script>
        window.alert('{{mensagens[0]}}')
    </script>
    {%endif%}
    <main class="input">
        <h1>SELECIONE O SEU SEXO</h1>
        <div class="variaveis-py">{{ progresso }}</div>
        <form action="{{ url_for('cadastro.genero_v') }}" method="post" class="form" id="form-p" >
            <div class="item">
                <input type="radio" name="gender"  value="feminino" >
                <label for="fem">Fem</label>
            </div>
            <div class="item">
                <input type="radio" name="gender"  value="masculino" >
                <label for="masc">Masc</label>
            </div>
            <div class="item-grande">
                <input type="radio" name="gender"  value="outro" required>
                <label for="outro">Prefiro não responder</label>
            </div>
        </form>
    </main>
    <footer class="div_botao">    
        <button class="botao" onclick="window.location.assign('/cadastro/cpf')" id="anterior"> <= Anterior</button>
        <div class="meio">
            <section class="progresso">
                <div class="range">
                    <div class="completado"></div>
                </div>
                <h3>% Completado</h3>
            </section>
            <aside><span>&#169;</span> made by UFMS</aside>
        </div>
            <button class="botao"  form="form-p"  type="submit" id="proximo">Próxima =></button>
    </footer>
    <script src="{{ url_for('static', filename= 'script.js') }}"></script>
</body>
</html>